apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-backend
  namespace: chatbot
spec:
  replicas: 1

  selector:
    matchLabels:
      app: chatbot-backend

  template:
    metadata:
      labels:
        app: chatbot-backend

    spec:
      containers:

      - name: backend

        image: rahulloganathan/chatbot-backend:259b6d6b25402c50842ceed75f03a78aa3cb6bbf

        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-secret
              key: api-key

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
