apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
  namespace: chatbot

spec:
  replicas: 1

  selector:
    matchLabels:
      app: chatbot-frontend

  template:
    metadata:
      labels:
        app: chatbot-frontend

    spec:

      containers:

      - name: frontend

        image: rahulloganathan/chatbot-frontend:331bf9371810d418840380633b6f3e1a421404a1

        imagePullPolicy: Always

        ports:
        - containerPort: 8501

        # env:
        # - name: BACKEND_URL
        #   value: "http://chatbot-backend:8000/chat"

        resources:

          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
